# Generated by Django 3.2.19 on 2023-08-18 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='Ad')),
                ('post_subtitle', models.TextField(verbose_name='Altyazı')),
                ('post_article', models.TextField(verbose_name='Məzmun')),
                ('post_date', models.DateTimeField(default=datetime.datetime(2023, 8, 18, 10, 20, 34, 279786), verbose_name='Tarix')),
                ('post_image_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Link')),
                ('post_image1', models.ImageField(upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
                ('post_image2', models.ImageField(upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
                ('post_image3', models.ImageField(blank=True, null=True, upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
                ('post_image4', models.ImageField(blank=True, null=True, upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
                ('post_image5', models.ImageField(blank=True, null=True, upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
                ('post_image6', models.ImageField(blank=True, null=True, upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
                ('post_image7', models.ImageField(blank=True, null=True, upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
                ('post_image8', models.ImageField(blank=True, null=True, upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
                ('post_image9', models.ImageField(blank=True, null=True, upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
                ('post_image10', models.ImageField(blank=True, null=True, upload_to='BlogPosts/%Y/%m/%d/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
