# Generated by Django 3.2.19 on 2023-08-18 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 10, 22, 36, 521003), verbose_name='Tarix'),
        ),
    ]
