# Generated by Django 3.2.19 on 2023-08-18 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 14, 40, 48, 506604), verbose_name='Tarix'),
        ),
    ]
