# Generated by Django 3.2.19 on 2023-08-24 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogmodel_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 2, 16, 10, 845299), verbose_name='Tarix'),
        ),
    ]
