# Generated by Django 4.2.4 on 2023-08-25 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogmodel_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 3, 55, 45, 637147), verbose_name='Tarix'),
        ),
    ]
