# Generated by Django 3.2.19 on 2023-08-18 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_price', models.FloatField(verbose_name='Price')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 8, 18, 10, 20, 34, 275253), verbose_name='Start date')),
                ('final_date', models.DateTimeField(verbose_name='Final date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.productmodel')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
    ]
