# Generated by Django 3.2.19 on 2023-08-18 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_campaignmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 14, 40, 48, 505049), verbose_name='Start date'),
        ),
    ]
