# Generated by Django 4.2.4 on 2023-08-25 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_campaignmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 14, 28, 49, 373499), verbose_name='Start date'),
        ),
    ]
