# Generated by Django 4.2.4 on 2023-08-25 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_campaignmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 3, 55, 45, 636645), verbose_name='Start date'),
        ),
    ]
