# Generated by Django 3.2.19 on 2023-08-18 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, validators=[property.models.validate_single_word], verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product name')),
                ('product_price', models.FloatField(verbose_name='Product price')),
                ('product_article', models.TextField(verbose_name='Product article')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 18, 10, 20, 34, 274110), verbose_name='Date')),
                ('square', models.FloatField(default=15.0, verbose_name='Square')),
                ('rooms', models.IntegerField(default=1, verbose_name='Rooms')),
                ('image1', models.ImageField(upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('image2', models.ImageField(upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.areamodel')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.categorymodel')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
