# Generated by Django 3.2.19 on 2023-08-18 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20230818_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='area',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 14, 37, 39, 911388), verbose_name='Date'),
        ),
    ]
