# Generated by Django 3.2.19 on 2023-08-24 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230818_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 16, 41, 15, 919483), verbose_name='Date'),
        ),
    ]
