# Generated by Django 4.2.4 on 2023-08-25 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_auto_20230825_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 14, 28, 49, 372808), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 14, 28, 49, 372070), verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='CommentReplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(verbose_name='Reply')),
                ('reply_date', models.DateTimeField(default=datetime.datetime(2023, 8, 25, 14, 28, 49, 373157), verbose_name='Reply date')),
                ('main_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.commentmodel')),
                ('user_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reply',
                'verbose_name_plural': 'replies',
            },
        ),
    ]
