# Generated by Django 4.2.4 on 2023-08-25 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_commentmodel_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreplymodel',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.productmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 23, 32, 31, 389986), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='commentreplymodel',
            name='reply_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 23, 32, 31, 390412), verbose_name='Reply date'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 23, 32, 31, 389036), verbose_name='Date'),
        ),
    ]
